### ISSUE TITLE
[Question] Continuous deployment - any insight on how you handle

### ISSUE THREAD

**Issue by syffs** [actionml/chef-machine#1]
Sorry for asking but I'm a bit lost on how you handle the continuous deployment...

If I understand well, you use:
- Terraform to instantiate the machines
- Terraform chef provisioner: Do you use it? Solo or client/server?
- This chef cookbook to install the pre-requisites: "Invoked by cloud-init", how do you use cloud-init?
- I guess you use some other chef cookbook for deploying pio cluster but I can't find which one?

Thanks in advance!

**Comment by dennybaa** [comment]
Hey, no problem

actually intent of use of this repo is very limited, cookbook installs the core containers nomad, swarm, consul etc, I wouldn't advise doing anything this way, there are better approaches out there :)

1) yup terraform
2) I use solo, but not TF chef provisioner.
3) yes it's invoked by cloud-init, here is only the part which gets chef https://github.com/stackfeed/cloud-init-data/blob/master/get-chef.cc. Further the custom "user-data" starts up chef which starts up "only" the core containers.
4) the pio cookbook which is publicly available here https://github.com/actionml/chef-pio as you already know, but there's no another "cookbook deploying pio cluster" which is publicly available.

**Comment by pferrel** [comment]
We have a private repo where we keep the terraform part of the automation. It is not publically supported. We use if for cluster (PVC) deployments on AWS for our clients.

All of the open repos are available as-is with no support beyond what the community provides.

Post questions on the google group if you wish: https://groups.google.com/forum/#!forum/actionml-user
